# Workflow https://github.com/marketplace/actions/run-shellcheck-with-reviewdog

name: ShellCheck Review

on:
  push: 
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          pattern: "*.sh"
          exclude: "./.git/*"
          shellcheck_flags: --external-sources --severity=info
          level: info
          fail_level: warning

  shellcheck_pr:
    if: github.event_name == 'pull_request'
    name: ShellCheck PR Review
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run ShellCheck with PR comments
        uses: reviewdog/action-shellcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review 
          #path: "."
          pattern: "*.sh" # Only check .sh files
          exclude: "./.git/*" # Optional.
          shellcheck_flags: --external-sources --severity=warning
          level: warning
